### ISSUE TITLE
Initial design for test automation

### ISSUE THREAD

**Issue by knowittobias** [knowitrickard/FlexiCharge-Test-and-integration#1]
Come up with a case where test automation would be a good fit.
What is easiest to test?
What gives most value?
Where do we have most logic to test?

**Comment by Khonin** [comment]
Our initial plan is to create 2 automated test cases

- One case for OCPP communication between charger and backend to validate messages and responses
- And one for validating REST API calls to the backend.

**Comment by Khonin** [comment]
Do you think this is a good start @knowittobias ?
Or do you have another vision to how we should approach this issue?
