### ISSUE TITLE
OCPP: Create test to assert ocpp endpoints work as expected

### ISSUE THREAD

**Issue by Khonin** [knowitrickard/FlexiCharge-Test-and-integration#9]
Create a test case to assert the response from the ocpp communication is as expected
within python pytest
- [x] Success when correct data is sent
- [x] Failure when incorrect data is sent

**Comment by Khonin** [comment]
This task has been delayed.
The OCPP team will provide endpoints that we should use instead of creating our own websocket to test with

**Comment by striris** [comment]
I have added the code into the main repo of T$I
